### ISSUE TITLE
ToggleMenu not working?

### ISSUE THREAD

**Issue by mguillen** [jdehlin/Xamarin-Sidebar#12]
Whenever I call SidebarNavigation.SidebarController.ToggleMenu(); the error below shows up:

"An object reference is required to access a non-static member `SidebarNavigation.SidebarController.ToggleMenu()`"

**Comment by jdehlin** [comment]
You have to create an instance of SidebarController before you can use it. Please reference the README and example projects for setup instructions.

**Comment by mguillen** [comment]
Sir @jdehlin The problem is I can't fully follow the setup instructions from the example projects, since I'm using Storyboard.

**Comment by mguillen** [comment]
Below is the error I get after adding a reference to the SidebarController:

"Object reference not set to an instance of an object"

@jdehlin 
@pilouk
