### ISSUE TITLE
Can i use it with MvvmCross?

### ISSUE THREAD

**Issue by alexrainman** [jdehlin/Xamarin-Sidebar#14]
Is it possible?

**Comment by alexrainman** [comment]
Will answer this myself: It works! Will upload demo project soon!

**Comment by jdehlin** [comment]
Glad you were able to get it to work! I would love to see the demo when you get a chance to upload it.

Thanks!

**Comment by alexrainman** [comment]
Here you have: https://github.com/alexrainman/MvvmCross.FlyOutMenu

Thank you!

**Comment by jdehlin** [comment]
Very cool project! Thanks again!

**Comment by alexrainman** [comment]
Any plans to give sidebar navigation Unified API support fro 64 bits? Soon only 64 bits apps con Apple Store.

**Comment by jdehlin** [comment]
Unified API support has been added.

**Comment by alexrainman** [comment]
Really? Well, cannot add the component to Unified project, it is not available.

**Comment by jdehlin** [comment]
Sorry I should have specified. There is a Unified version in the
repository. I'm told the component with Unified support should should be
approved and released in January.

Jack
