### ISSUE TITLE
Upgrade failure from v2 to v3 on Xamarin.iOS project

### ISSUE THREAD

**Issue by atokuswanto** [jdehlin/Xamarin-Sidebar#87]
## 🐛 Bug Report

I tried upgrading v2.1.0 to latest v3.0.0 on my Xamarin.iOS project. I got error message in Package console.

Could not install package 'SidebarNavigation 3.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Configuration
Current package.config file has entry like this:
`<package id="SidebarNavigation" version="2.1.0" targetFramework="xamarinios10" />`

**Version:** 3.0.0

**Platform:** 
- [x] :iphone: iOS

**Comment by martijn00** [comment]
V3 only supports .net6 or higher

**Comment by atokuswanto** [comment]
@martijn00  v3 cannot be used on Xamarin.iOS project?
Or, can you please guide me how can I config my Xamarin.iOS project to use v3?

**Comment by martijn00** [comment]
Xamarin.iOS doesn't exist anymore. Use .NET MAUI and .net6-ios targets
