### ISSUE TITLE
Menu when taking a picture with Camera.cs have a bad offset on callback (extra white space)

### ISSUE THREAD

**Issue by pilucdes** [jdehlin/Xamarin-Sidebar#9]
Here what i found, it's seem that on the callback of the camera in
the ViewWillAppear method of sidebarcontroller, the MenuAreaController.Frame.Width  is less than the width of the screen for some reason. So the navigationFrame.X have a bad offset (i use right menu). This only occur in Portrait and taking camera with UIimagePicker.

Note that after taking a picture in portrait and having the extra white space i rotate my phone landscape and rotate it again in portrait the
sidebar fix itself.

![img_0008](https://cloud.githubusercontent.com/assets/1840762/4602612/9bc69408-5142-11e4-8e66-b46d66abf858.PNG)

**Comment by jdehlin** [comment]
Thanks for your help tracking this one down. Your suggestion of SetNeedsLayout did the trick. The updated component should be up in a couple of days.

Thanks again!

**Comment by pilucdes** [comment]
No problem, your sidemenu is the best out there. It was the least I could do!
